In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

In [5]:
print arr

[1 2 3]


In [6]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

** arange **

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((3,4)) #pass tuple

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [15]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

** linspace **

In [16]:
np.linspace(1, 10, 20)

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

** eye ** is Identity Matrix

In [18]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random 

1) ** rand(n) ** : gives 'n' number of randomly distributed float numbers in **[0,1)**

In [20]:
np.random.rand(5)

array([ 0.87301612,  0.02961838,  0.84679902,  0.50138317,  0.71185438])

In [21]:
np.random.rand(5,5)

array([[ 0.16266283,  0.27290152,  0.62935159,  0.80722588,  0.34400511],
       [ 0.67375325,  0.37475247,  0.63404306,  0.78074741,  0.64244006],
       [ 0.79359752,  0.16471338,  0.16908626,  0.36107846,  0.84184472],
       [ 0.587788  ,  0.26462244,  0.90738482,  0.21911139,  0.03106273],
       [ 0.38184589,  0.12692691,  0.85575112,  0.49581126,  0.25073025]])

2) <br>
** randint(n) ** will give one random integer < n <br>
** randint(m,n) ** will give one random integer i, m <= i < n  <br>
** randint(m,n,k) ** will give **'k'** random integers i[k], m <= i[k] < n

In [25]:
np.random.randint(1,100,5)

array([14, 64, 25, 45, 98])

3) <br>
** randn(m) ** : returns 'm' floats using gaussian distribution centered around ** 0 ** <br>
** randn(m,n) ** : returns 'm x n' matrix of floats using gaussian distribution centered around ** 0 ** <br>

In [26]:
np.random.randn(4,2)

array([[ 0.61722985,  1.42502178],
       [ 1.21110556, -1.09592966],
       [-1.32520262, -0.42079104],
       [-0.84135563,  0.33908619]])

#### Array operations

In [27]:
arr = np.arange(25)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr = np.random.randint(1,100,10)

In [30]:
print ranarr

[22 90 48 39 64 13 38 99 63  1]


In [31]:
ranarr.max()

99

In [32]:
ranarr.min()

1

In [33]:
ranarr.argmax()

7

In [34]:
ranarr.argmin()

9

In [36]:
arr.shape

(25,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int64')